# https://github.com/marketplace/actions/pypi-publish
name: Publish to PyPi

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

